### ISSUE TITLE
MMM-Strava is no longer working?

### ISSUE THREAD

**Issue by slametps** [ianperrin/MMM-Strava#72]
When submitting a new issue, please supply the following information:

Platform (Hardware/OS): Raspberry 4B

Node Version: 9.5.1

MagicMirror Version: 2.22.0

Description: Got error message on MagicMirror display with error message "Strava Authorisation has changed. Please update your config".

Steps to Reproduce: run MM 
Expected Results: my ride stats on Strava
Actual Results: got text "Client id unauthorised - please visit /MMM-Strava/auth"

Configuration:
```
{ 
			module: 'MMM-Strava',
			classes: 'default everyone',
			position: "top_left",
			config: {
				strava_id: '25594789',
				access_token: '[REMOVED]',
				client_id: '21378',
				client_secret: '[REMOVED]',
				mode: 'chart',
				//activities: ["run", "ride", "swim"],
				activities: ["ride"],
				auto_rotate: true,
				updateInterval: 10 * 1000,
				reloadInterval: 60 * 60 * 1000,
				animationSpeed: 2500,
			}
		}
```

Additional Notes: 
Got following error log on MM logs:
```
[25.02.2023 13:19.12.221] [WARN]  Unhandled rejection StatusCodeError: 401 - {"message":"Authorization Error","errors":[{"resource":"Application","field":"","code":"invalid"}]}
    at new StatusCodeError (/home/slametps/work/MagicMirror/modules/MMM-Strava/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/home/slametps/work/MagicMirror/modules/MMM-Strava/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/home/slametps/work/MagicMirror/modules/MMM-Strava/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/home/slametps/work/MagicMirror/modules/MMM-Strava/node_modules/request/request.js:185:22)
    at Request.emit (node:events:513:28)
    at Request.<anonymous> (/home/slametps/work/MagicMirror/modules/MMM-Strava/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:513:28)
    at IncomingMessage.<anonymous> (/home/slametps/work/MagicMirror/modules/MMM-Strava/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:627:28)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

![MM-error-MMM-Strava-unauthorized](https://user-images.githubusercontent.com/20857805/221342211-6e3f2c23-42d9-4104-88e7-f72bf82020ac.png)

**Comment by RubenRybnik88** [comment]
Worked for me, but I had to change the 'Authorisation Callback Domain' in Strava API to be ''exactly'' the same as my hostname, which is an IP on my internal network in this case. Couldn't use localhost:8080 etc. Then the auth process triggered fine.

<img width="422" alt="image" src="https://user-images.githubusercontent.com/119454271/221439534-5c00e93e-729a-4230-8943-09366ab854ae.png">

![image](https://user-images.githubusercontent.com/119454271/221439809-5b4a312e-e537-405b-a6f2-6734a959e809.png)

**Comment by yexner** [comment]
Thanks @RubenRybnik88, 
I gave this  try as well, however still received the "bad request" message, as shown below after clicking the "Authorise" button under '<local_ip>:8080/MMM-Strava/auth/'.

Any other idea?

![image](https://user-images.githubusercontent.com/65974612/228046606-a6913425-dedf-4d7f-bb32-6e2ae71f3bd8.png)

**Comment by zynapsid** [comment]
@RubenRybnik88 Is this still working for you (if you still use it at all?)
